#!/usr/bin/env python3
"""Rebuilds the generated SanMar section of js/sanmar-catalog.js.

Run from the repo root:  python3 tools/build_catalog.py

Source list: tools/sanmar-products.json (style, brand, name, cat).
Photos live in images/blanks/<STYLE>.jpg. Styles that already exist as
hand-written products (js/products-data.js or the top of js/sanmar-catalog.js)
are skipped so nothing is listed twice.
"""
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
START = "/* sanmar-brands:start (generated by tools/build_catalog.py - do not edit by hand) */"
END = "/* sanmar-brands:end */"
COLOR = {"tshirts": "#26400f", "activewear": "#1e6a3d", "hoodies": "#1c1c1c", "outerwear": "#1c1c1c",
         "wovens": "#243b63", "bottoms": "#4a5850", "hats": "#243b63", "bags": "#4a5850", "promo": "#f5a623"}


def js(s):
    return json.dumps(s, ensure_ascii=False)


def main():
    target = ROOT / "js/sanmar-catalog.js"
    src = target.read_text()
    if START in src:
        src = src[:src.index(START)].rstrip() + "\n"
    existing = (ROOT / "js/products-data.js").read_text() + src
    have_styles = {s.upper() for s in re.findall(r'style:"([^"]+)"', existing)}
    have_ids = set(re.findall(r'\bid:"([^"]+)"', existing))

    rows = []
    for p in json.loads((ROOT / "tools/sanmar-products.json").read_text()):
        style = p["style"]
        if style in have_styles or not (ROOT / f"images/blanks/{style}.jpg").exists():
            continue
        pid = style.lower()
        while pid in have_ids:
            pid += "-b"
        have_ids.add(pid)
        blurb = f'{p["brand"]} {style} - {p["name"]}, ready for custom print or embroidery.'
        rows.append(
            f'  {{ id:{js(pid)}, name:{js(p["name"])}, brand:{js(p["brand"] + " " + style)}, mfr:{js(p["brand"])}, '
            f'style:{js(style)}, cat:{js(p["cat"])}, color:{js(COLOR.get(p["cat"], "#243b63"))}, work:null, blurb:{js(blurb)} }}')
    fixes = {k: v for k, v in json.loads((ROOT / "tools/category-overrides.json").read_text()).items() if not k.startswith("_")}
    block = (f"{START}\nwindow.MEADOW_PRODUCTS.push(\n" + ",\n".join(rows) + "\n);\n"
             "/* category corrections from tools/category-overrides.json (applies to every product, hand-written ones too) */\n"
             f"(function (fix) {{ window.MEADOW_PRODUCTS.forEach(p => {{ if (p.style && fix[p.style]) p.cat = fix[p.style]; }}); }})({json.dumps(fixes)});\n"
             f"{END}\n")
    target.write_text(src + "\n" + block)
    print(f"wrote {len(rows)} generated products")


if __name__ == "__main__":
    main()
